;///////////////////////////////////////////////////////////////////////////
;//
;//  Copyright (C) 1999 Microsoft Corporation.  All Rights Reserved.
;//
;//  File:       d3dx8.h
;//  Content:    D3DX utility library
;//
;///////////////////////////////////////////////////////////////////////////

%IFNDEF _D3DX8_INC_
%DEFINE _D3DX8_INC_

%include "dx\d3d8.inc"

%include "dx\d3dx8math.inc"

%include "dx\d3dx8core.inc"

%include "dx\d3dx8tex.inc"

%include "dx\d3dx8mesh.inc"

%include "dx\d3dx8effect.inc"

%ENDIF
